version: '3'

services:
  appskeleton_mysql_server:
    image: hypriot/rpi-mysql
    restart: unless-stopped
    container_name: appskeleton_mysql_server
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=appskeleton_user
      - MYSQL_ROOT_PASSWORD=hoJx6SM1T1QlCH
      - MYSQL_DATABASE=appskeleton_db
    ports:
      - "3306"

  appskeleton_phpadmin:
    image: phpmyadmin
    restart: unless-stopped
    container_name: appskeleton_phpadmin
    environment:
      PMA_HOST: appskeleton_mysql_server
      PMA_USER: root
      PMA_PASSWORD: hoJx6SM1T1QlCH
      PMA_PORT: 3306
    ports:
      - "8091:80"
    depends_on:
      - appskeleton_mysql_server
      
  appskeleton_app:
    image: kryptoncontainer/aspnetcore31appskeleton
    restart: unless-stopped
    container_name: appskeleton_app
    ports:
      - "8090:80"
    links:
      - appskeleton_mysql_server
    depends_on:
      - appskeleton_mysql_server
    environment:
      - ConnectionStrings:DefaultConnection=Server=appskeleton_mysql_server;Port=3306;DataBase=appskeleton_db;Uid=root;Pwd=hoJx6SM1T1QlCH